# Background and foreground colors
background = #0A141E
foreground = #F2E784

# Standard colors
palette = 0=#0A141E
palette = 1=#c08d5c
palette = 2=#eabf6f
palette = 3=#ffea8c
palette = 4=#b56f4f
palette = 5=#ea9a62
palette = 6=#ffd966
palette = 7=#F2E784

# Bright colors
palette = 8=#6a6e74
palette = 9=#df9f61
palette = 10=#ffd366
palette = 11=#ffe367
palette = 12=#d57f57
palette = 13=#ffa95f
palette = 14=#ffec54
palette = 15=#fcf4eb
