$color = rgba(10, 20, 30, 1)
$inner_color = rgba(10, 20, 30, 0.66)
$outer_color = rgba(234, 154, 98, 1)
$font_color = rgba(242, 231, 132, 1)
$placeholder_color = rgba(242, 231, 132, 0.7)
$check_color = rgba(255, 217, 102, 1)
