background            #0A141E
foreground            #F2E784

# black
color0  #0A141E
color8  #6a6e74

# red
color1  #c08d5c
color9  #df9f61

# green
color2  #eabf6f
color10 #ffd366

# yellow
color3  #ffea8c
color11 #ffe367

# blue
color4  #b56f4f
color12 #d57f57

# magenta
color5  #ea9a62
color13 #ffa95f

#cyan
color6  #ffd966
color14 #ffec54

#white
color7  #F2E784
color15 #fcf4eb


